const TraversalEventType = Object.freeze({
  TRACKING_STARTED: 'TRACKING_STARTED',
  ENTERED_SEGMENT: 'ENTERED_SEGMENT',
  ENTERED_BRANCH: 'ENTERED_BRANCH',
  ARRIVED_AT_STATION: 'ARRIVED_AT_STATION',
  DEPARTED_STATION: 'DEPARTED_STATION',
  PASSED_STATION: 'PASSED_STATION',
  DIRECTION_CHANGED: 'DIRECTION_CHANGED',
  LOST_TRACKING: 'LOST_TRACKING',
  TRACKING_RECOVERED: 'TRACKING_RECOVERED',
  IMPOSSIBLE_JUMP: 'IMPOSSIBLE_JUMP',
  PROJECTION_UPDATED: 'PROJECTION_UPDATED'
});

module.exports = {
  TraversalEventType
};
