const { validateInputs } = require('./validation.js');
const { evaluateCandidates } = require('./CandidateEvaluator.js');
const { selectBestCandidate } = require('./CandidateSelector.js');

/**
 * Projects a GPS point onto the closest valid topological branch within an assembled corridor.
 * Returns the exact ProjectionResult structure generated by the legacy projection engine.
 *
 * @param {Object} assembledCorridor The immutable AssembledCorridor
 * @param {Object} point The observation point {lat, lng}
 * @returns {Object|null} The unmodified ProjectionResult, or null if no valid projection
 */
function projectOntoCorridor(assembledCorridor, point) {
  // 1. Validate inputs
  validateInputs(assembledCorridor, point);

  // 2. Retrieve traversable segments from AssembledCorridor
  const segments = assembledCorridor.getTraversableSegments();

  // 3. Evaluate every segment
  const candidates = evaluateCandidates(segments, point);

  // 4. Select the mathematically closest valid projection
  return selectBestCandidate(candidates);
}

module.exports = {
  projectOntoCorridor
};
